# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-27 12:57
from __future__ import unicode_literals

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_name', models.CharField(max_length=14)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('is_forbidden', models.BooleanField(default=True)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
                ('admin_type', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatar_default.jpg', upload_to=b'')),
                ('user_describe', models.CharField(max_length=40)),
                ('type', models.IntegerField(default=0)),
                ('recommend_ticket_num', models.IntegerField(default=0)),
                ('diamond_ticket_num', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('chase_book', jsonfield.fields.JSONField(default={})),
                ('subscribe_book', jsonfield.fields.JSONField(default={})),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
