# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-28 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatar_default.jpg', upload_to=b''),
        ),
    ]
