# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-08 05:08
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20171228_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chase_book',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscriber_book',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
