# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-09 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180108_0508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='subscriber_book',
            new_name='subscribe_book',
        ),
    ]
