# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-27 12:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='\u533f\u540d', max_length=6)),
                ('book_name', models.CharField(max_length=15)),
                ('cover', models.ImageField(default='', upload_to=b'')),
                ('describe', models.TextField(max_length=300)),
                ('book_type', models.SmallIntegerField(choices=[(0, '\u4ed9\u5251'), (1, '\u7384\u5e7b'), (2, '\u60ac\u7591'), (3, '\u5947\u5e7b'), (4, '\u519b\u4e8b'), (5, '\u5386\u53f2'), (6, '\u7ade\u6280'), (7, '\u79d1\u5e7b'), (8, '\u6821\u56ed'), (9, '\u793e\u4f1a'), (10, '\u5176\u5b83')])),
                ('word_number', models.IntegerField(default=0)),
                ('update_state', models.SmallIntegerField(default=0)),
                ('chapter_num', models.IntegerField(default=0)),
                ('book_money', models.IntegerField(default=0)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('isShow', models.BooleanField(default=True)),
                ('auditingState', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='BookChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_id', models.SmallIntegerField()),
                ('chapter_name', models.CharField(max_length=20)),
                ('chapter_content', models.TextField()),
                ('word_number', models.IntegerField(default=0)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('chapter_type', models.IntegerField(choices=[(0, '\u514d\u8d39'), (1, '\u6536\u8d39'), (2, '\u5df2\u4ed8\u8d39')], default=0)),
                ('chapter_state', models.IntegerField(choices=[(0, '\u4e0d\u53d1\u5e03'), (1, '\u53d1\u5e03')], default=0)),
                ('chapter_money', models.IntegerField(default=0)),
                ('chapter_PV', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'book_chapter',
            },
        ),
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.IntegerField(choices=[(0, '\u4e00\u822c'), (1, '\u7cbe\u534e'), (2, '\u7f6e\u9876'), (3, '\u7cbe\u534e\u5e76\u7f6e\u9876')], default=0)),
                ('comment_content', models.CharField(max_length=120)),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'book_comment',
            },
        ),
        migrations.CreateModel(
            name='BookProfile',
            fields=[
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reading.Book')),
                ('book_rank', models.SmallIntegerField(default=0)),
                ('click_num', models.IntegerField(default=0)),
                ('subscriber_num', models.IntegerField(default=0)),
                ('chase_book_num', models.IntegerField(default=0)),
                ('reward_num', models.IntegerField(default=0)),
                ('cat_ball_num', models.IntegerField(default=0)),
                ('catnip_num', models.IntegerField(default=0)),
                ('cat_stick_num', models.IntegerField(default=0)),
                ('cat_food_num', models.IntegerField(default=0)),
                ('cat_fish_num', models.IntegerField(default=0)),
                ('cat_house_num', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'book_profile',
            },
        ),
        migrations.AddField(
            model_name='bookcomment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_comment', to='reading.Book'),
        ),
        migrations.AddField(
            model_name='bookcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookchapter',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_chapter', to='reading.Book'),
        ),
    ]
