# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-09 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='\u533f\u540d', max_length=6, verbose_name='\u4f5c\u8005')),
                ('book_name', models.CharField(max_length=15, verbose_name='\u4e66\u540d')),
                ('cover', models.ImageField(upload_to=b'', verbose_name='\u5c01\u9762')),
                ('describe', models.TextField(max_length=300, verbose_name='\u6982\u8981')),
                ('type', models.SmallIntegerField(choices=[(1, '\u4ed9\u5251'), (2, '\u7384\u5e7b'), (3, '\u60ac\u7591'), (4, '\u5947\u5e7b'), (5, '\u519b\u4e8b'), (6, '\u5386\u53f2'), (7, '\u7ade\u6280'), (8, '\u79d1\u5e7b'), (9, '\u6821\u56ed'), (10, '\u793e\u4f1a'), (11, '\u5176\u5b83')], verbose_name='\u7c7b\u578b')),
                ('word_number', models.IntegerField(default=0, verbose_name='\u5b57\u6570')),
                ('update_state', models.SmallIntegerField(default=0, verbose_name='\u66f4\u65b0\u72b6\u6001')),
                ('chapter_num', models.IntegerField(default=0, verbose_name='\u7ae0\u8282\u6570\u91cf')),
                ('book_money', models.IntegerField(default=0, verbose_name='\u4e66\u7c4d\u4ef7\u683c')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='BookProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reading.Book')),
            ],
            options={
                'db_table': 'book_profile',
            },
        ),
    ]
