# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-27 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='auditingState',
            new_name='auditing_state',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='isShow',
            new_name='is_show',
        ),
    ]
