# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-28 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='auditingState',
            field=models.BooleanField(default=0, verbose_name='\u5ba1\u6838\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='book',
            name='isShow',
            field=models.BooleanField(default=True, verbose_name='\u662f\u5426\u663e\u793a'),
        ),
        migrations.AddField(
            model_name='bookprofile',
            name='catBallNumber',
            field=models.IntegerField(default=0, verbose_name='\u732b\u7403\u6253\u8d4f\u603b\u91cf'),
        ),
        migrations.AddField(
            model_name='bookprofile',
            name='catFishNumber',
            field=models.IntegerField(default=0, verbose_name='\u8dd1\u722c\u67b6\u6253\u8d4f\u603b\u91cf'),
        ),
        migrations.AddField(
            model_name='bookprofile',
            name='catFoodNumber',
            field=models.IntegerField(default=0, verbose_name='\u732b\u6293\u996d\u6253\u8d4f\u603b\u91cf'),
        ),
        migrations.AddField(
            model_name='bookprofile',
            name='catHouseNumber',
            field=models.IntegerField(default=0, verbose_name='\u732b\u7a9d\u6253\u8d4f\u603b\u91cf'),
        ),
        migrations.AddField(
            model_name='bookprofile',
            name='catStickNumber',
            field=models.IntegerField(default=0, verbose_name='\u9017\u732b\u68d2\u6253\u8d4f\u603b\u91cf'),
        ),
        migrations.AddField(
            model_name='bookprofile',
            name='catnipNumber',
            field=models.IntegerField(default=0, verbose_name='\u732b\u8584\u8377\u6253\u8d4f\u603b\u91cf'),
        ),
        migrations.AddField(
            model_name='bookprofile',
            name='chaseBooksNumber',
            field=models.IntegerField(default=0, verbose_name='\u8ffd\u4e66\u91cf'),
        ),
        migrations.AddField(
            model_name='bookprofile',
            name='clicksNumber',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u91cf'),
        ),
        migrations.AddField(
            model_name='bookprofile',
            name='reward',
            field=models.IntegerField(default=0, verbose_name='\u732b\u5e01\u6253\u8d4f\u603b\u6570'),
        ),
        migrations.AddField(
            model_name='bookprofile',
            name='subscribersNumber',
            field=models.IntegerField(default=0, verbose_name='\u8ba2\u9605\u91cf'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='', upload_to=b'', verbose_name='\u5c01\u9762'),
        ),
    ]
