# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-28 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_auto_20171228_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookprofile',
            old_name='catBallNumber',
            new_name='cat_ball_num',
        ),
        migrations.RenameField(
            model_name='bookprofile',
            old_name='catFishNumber',
            new_name='cat_fish_num',
        ),
        migrations.RenameField(
            model_name='bookprofile',
            old_name='catFoodNumber',
            new_name='cat_food_num',
        ),
        migrations.RenameField(
            model_name='bookprofile',
            old_name='catHouseNumber',
            new_name='cat_house_num',
        ),
        migrations.RenameField(
            model_name='bookprofile',
            old_name='catStickNumber',
            new_name='cat_stick_num',
        ),
        migrations.RenameField(
            model_name='bookprofile',
            old_name='catnipNumber',
            new_name='catnip_num',
        ),
        migrations.RenameField(
            model_name='bookprofile',
            old_name='chaseBooksNumber',
            new_name='chase_book_num',
        ),
        migrations.RenameField(
            model_name='bookprofile',
            old_name='clicksNumber',
            new_name='click_num',
        ),
        migrations.RenameField(
            model_name='bookprofile',
            old_name='reward',
            new_name='reward_num',
        ),
        migrations.RenameField(
            model_name='bookprofile',
            old_name='subscribersNumber',
            new_name='subscriber_num',
        ),
    ]
