# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_auto_20180127_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='describe',
            new_name='book_describe',
        ),
    ]
