# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-28 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_auto_20171228_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='bookprofile',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reading.Book'),
        ),
    ]
